/**
 * Turns a raw Figma logo export into the two files the site actually uses.
 *
 *   node scripts/build-logo.js src/assets/images/swd_wordmark_logo3.svg
 *
 * Writes:
 *   src/assets/svgs/logo-wordmark.svg          literal colours, for rasterising
 *   src/_includes/components/logo-wordmark.html inline + themeable, for the pages
 *
 * Why this exists: the logo went through three revisions in one sitting and each
 * one needed the same three fixes applied by hand. Doing it by eye invites a
 * transcription error in 9KB of path data, and the viewBox has to be measured
 * rather than guessed.
 *
 * The three fixes:
 *
 *  1. TIGHTEN THE VIEWBOX. Figma exports the artboard, not the artwork. Every
 *     export so far carried hundreds of units of empty space (v3: 316 on the
 *     left, 394 on the right). In a navbar that padding shoves the nav items
 *     away and leaves the logo looking mis-set against the container edge.
 *     Measured here by rendering at 3x and finding the real alpha bounds.
 *
 *  2. BLACK -> currentColor. Figma exports the type and the arc as #000000.
 *     Everything else on this site is inkNavy, and more importantly the lockup
 *     has to flip to warm white in dark mode and on the navy footer. Only
 *     currentColor can do that.
 *
 *  3. WAVES -> a custom property. --logoWave is defined in root.less and
 *     overridden on every navy surface, so the water lightens where #2e4865
 *     would disappear. The literal after the comma is a fallback.
 *
 * The inline component exists because an <img src="...svg"> is an opaque
 * document: CSS on the page cannot reach the fills inside it, so the type could
 * never flip. Same reason components/socials.html is inline.
 */
const fs = require("fs");
const path = require("path");
const sharp = require("sharp");

const SRC = process.argv[2];
if (!SRC || !fs.existsSync(SRC)) {
    console.error("usage: node scripts/build-logo.js <path-to-figma-export.svg>");
    process.exit(1);
}

const OUT_SVG = "src/assets/svgs/logo-wordmark.svg";
const OUT_INC = "src/_includes/components/logo-wordmark.html";

(async () => {
    const src = fs.readFileSync(SRC).toString();
    const dims = src.match(/width="(\d+)"\s+height="(\d+)"/);
    if (!dims) throw new Error("no width/height on the root <svg>");
    const W = +dims[1], H = +dims[2];

    // ── measure the real artwork bounds ──────────────────────────────────────
    // Rendered at 3x so a half-unit edge doesn't round away.
    const S = 3;
    const png = await sharp(Buffer.from(src.replace(dims[0], `width="${W * S}" height="${H * S}"`)))
        .png().toBuffer();
    const { data, info } = await sharp(png).ensureAlpha().raw().toBuffer({ resolveWithObject: true });
    let x1 = Infinity, y1 = Infinity, x2 = -1, y2 = -1;
    for (let y = 0; y < info.height; y++) {
        for (let x = 0; x < info.width; x++) {
            if (data[(y * info.width + x) * 4 + 3] > 10) {
                if (x < x1) x1 = x; if (x > x2) x2 = x;
                if (y < y1) y1 = y; if (y > y2) y2 = y;
            }
        }
    }
    const bx = x1 / S, by = y1 / S, bw = (x2 - x1) / S, bh = (y2 - y1) / S;
    const viewBox = `${bx.toFixed(1)} ${by.toFixed(1)} ${bw.toFixed(1)} ${bh.toFixed(1)}`;

    // ── remap fills ──────────────────────────────────────────────────────────
    const paths = [...src.matchAll(/<path\b[^>]*\/>/g)].map((m) => m[0]);
    if (!paths.length) throw new Error("no <path> elements found");
    const remap = (p, mode) => {
        const isWave = /#2E4865/i.test(p);
        const fill = mode === "literal"
            ? (isWave ? "#2e4865" : "#1b2a38")
            : (isWave ? "var(--logoWave, #2e4865)" : "currentColor");
        return p.replace(/fill="[^"]*"/, `fill="${fill}"`);
    };

    fs.writeFileSync(OUT_SVG,
        `<!-- Generated by scripts/build-logo.js from ${path.basename(SRC)}. Do not hand-edit.\n` +
        `     Literal colours on purpose: this is the source for favicons and the\n` +
        `     og:image, which rasterise with no stylesheet to inherit from. -->\n` +
        `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}" role="img" aria-label="Shoreline Web Design">\n` +
        paths.map((p) => "  " + remap(p, "literal")).join("\n") + "\n</svg>\n");

    fs.writeFileSync(OUT_INC,
        `{#\n  Shoreline Web Design wordmark. GENERATED by scripts/build-logo.js from\n` +
        `  ${SRC} - do not hand-edit, rerun the script.\n\n` +
        `  Inline rather than <img src>, because an <img> is an opaque document and\n` +
        `  CSS cannot reach the fills inside it. The type has to flip to warm white\n` +
        `  in dark mode and on the navy footer, so it must be reachable.\n\n` +
        `  - type + arc: currentColor, so the lockup follows .cs-logo's colour\n` +
        `  - waves: --logoWave, overridden on every navy surface in root.less\n\n` +
        `  aria-hidden because the parent <a> carries aria-label="Shoreline Web\n` +
        `  Design home". Announcing it twice makes a screen reader read the business\n` +
        `  name twice for one link. Don't add visible text beside it either - the\n` +
        `  wordmark IS the text.\n\n` +
        `  Artwork ${bw.toFixed(0)}x${bh.toFixed(0)}, ratio ${(bw / bh).toFixed(2)}:1. Height drives width in root.less.\n#}\n` +
        `<svg class="cs-logo-wordmark" viewBox="${viewBox}" aria-hidden="true" focusable="false" xmlns="http://www.w3.org/2000/svg">\n` +
        paths.map((p) => "    " + remap(p, "theme")).join("\n") + "\n</svg>\n");

    console.log(`  source   ${SRC}`);
    console.log(`  artboard ${W} x ${H}`);
    console.log(`  artwork  ${bw.toFixed(1)} x ${bh.toFixed(1)}   ratio ${(bw / bh).toFixed(2)}:1`);
    console.log(`  viewBox  "${viewBox}"`);
    console.log(`  wrote    ${OUT_SVG}`);
    console.log(`  wrote    ${OUT_INC}`);
})();
